### ISSUE TITLE
Huge macos bug

### ISSUE THREAD

**Issue by amichaeel** [jjcxdev/vim#19]
When switching from macbook to apple, the website becomes unusable and glitches with everything stuttering. If i try to go back to macbook, it my own computer becomes unusable and browser just quits itself. My dock also becomes unresponsive and requires a restart.

**Comment by jjcxdev** [comment]
Looks like an issue I fixed earlier didn't update properly. I know what's causing that. Should have a fix in the next couple of hours.

Many apologies.

**Comment by jjcxdev** [comment]
> When switching from macbook to apple, the website becomes unusable and glitches with everything stuttering. If i try to go back to macbook, it my own computer becomes unusable and browser just quits itself. My dock also becomes unresponsive and requires a restart. 

Looks like an issue I fixed earlier didn't update properly. I know what's causing that. Should have a fix in the next couple of hours.

Many apologies.
